### ISSUE TITLE
preprocess.py (works with benchmark data sets)

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/LGBM#6]

**Comment by adpartin** [comment]
@wilke I assume this is triggered from Projects https://github.com/orgs/JDACS4C-IMPROVE/projects/8. We currently don't have `preprocess.py`, `train.py`, `infer.py`. Instead, we require `MODELNAME_preprocess_improve.py`, `MODELNAME_train_improve.py`, `MODELNAME_infer_improve.py`. Should we update the requirements in the Projects?
