### ISSUE TITLE
Change to output_dir

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/LGBM#7]
https://github.com/JDACS4C-IMPROVE/LGBM/blame/2bc3c97ba92458835fd079773bb51994ddbccdf8/lgbm_preprocess_improve.py#L139

Why is there a ml_out_dir , convention is output_dir

**Comment by adpartin** [comment]
IIRC, output_dir is a known CANDLE param, and it is used to output any results from a candlized python script. In IMPROVE, we currently enforce to create 3 scripts, each responsible for the different step in the ML workflow. When I was designing the framework and the CSA workflow (csa_wf*.py), it was more convenient for me to separate the outputs. I think it should be possible to output_dir instead. But if possible, I prefer to stay with the existing structure for the upcoming release. What do you think?

**Comment by wilke** [comment]
Solved, general parameters are input_dir and output_dir for all model scripts.
